version: '3'
services:
  api:
    build: .
    restart: always
    ports:
      - '5000'
  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    links:
      - api
    depends_on:
      - api
